#!/usr/bin/php -q

<?php
  
  if(PHP_SAPI != 'cli')
  {
    die('This is a shell application, so make sure to run this application in your terminal.');
  }
  
  ini_set('memory_limit', '500M');
  
  include_once('inc/OSFInstaller.php');
  include_once('inc/OSFInstaller_Ubuntu_12_10.php');
  
  $installer;
  
  // Detects what is the version of the current linux distribution.
  // Let's use the installer for the good distribution and the good version.
  // If the distribution/version is not supported, the generic installer
  // will be used which means that some features may be disabled.
  if(OSFInstaller_Ubuntu_12_10::isWorkingInstaller())
  {
    $installer = new OSFInstaller_Ubuntu_12_10(getcwd().'/installer.ini');  
  }
  else
  {
    $installer = new OSFInstallerGeneric(getcwd().'/installer.ini');
  }
  
  
  
  // Get commandline options
  $arguments = getopt('h::v::', array('help::',
                                      'verbose::',
                                      'install-osf::',
                                      'install-apache2::',
                                      'install-mysql::',
                                      'install-phpmyadmin::',
                                      'install-php5::',
                                      'install-virtuoso::',
                                      'install-solr::',
                                      'install-structwsf::',
                                      'install-structwsf-php-api::',
                                      'upgrade-structwsf-php-api::',
                                      'install-structwsf-tests-suites::',
                                      'upgrade-structwsf-tests-suites::',
                                      'install-datasets-management-tool::',
                                      'upgrade-datasets-management-tool::',  
                                      'install-ontologies-management-tool::',
                                      'upgrade-ontologies-management-tool::'));  
  
  // Displaying DSF's help screen if required
  if(isset($arguments['h']) || isset($arguments['help']))
  {
    $installer->cecho("Usage: osf-install [OPTIONS]\n\n\n", 'WHITE');
    $installer->cecho("General Options:\n", 'WHITE');
    $installer->cecho("-h, --help                              Show this help section\n", 'WHITE');
    $installer->cecho("-v, --verbose                           Make this insaller verbose\n\n", 'WHITE');
    $installer->cecho("Installation Options:\n", 'WHITE');
    $installer->cecho("--install-osf                           Install the Open Semantic Framework \n", 'WHITE');
    $installer->cecho("--install-apache2                       Install Apache2 \n", 'WHITE');
    $installer->cecho("--install-mysql                         Install MySQL \n", 'WHITE');
    $installer->cecho("--install-phpmyadmin                    Install PhpMyAdmin \n", 'WHITE');
    $installer->cecho("--install-virtuoso                      Install Virtuoso \n", 'WHITE');
    $installer->cecho("--install-solr                          Install Solr \n", 'WHITE');
    $installer->cecho("--install-php5                          Install PHP5 \n", 'WHITE');
    $installer->cecho("--install-structwsf-php-api             Install the structWSF-PHP-API library \n", 'WHITE');
    $installer->cecho("--install-structwsf-tests-suites        Install the structWSF tests suites \n", 'WHITE');
    $installer->cecho("--install-datasets-management-tool      Install the Datasets Management Tool \n", 'WHITE');
    $installer->cecho("--install-ontologies-management-tool    Install the Ontologies Management Tool \n", 'WHITE');
    $installer->cecho("\nUpgrade Options:\n", 'WHITE');
    $installer->cecho("--upgrade-structwsf-php-api             Upgrade the structWSF-PHP-API library \n", 'WHITE');
    $installer->cecho("--upgrade-structwsf-tests-suites        Upgrade the structWSF tests suites \n", 'WHITE');
    $installer->cecho("--upgrade-datasets-management-tool      Upgrade the Datasets Management Tool \n", 'WHITE');
    $installer->cecho("--upgrade-ontologies-management-tool    Upgrade the Ontologies Management Tool \n", 'WHITE');
    $installer->cecho("\n\n", 'WHITE');
    die;
  }

  // Make the output more verbose
  if(isset($arguments['v']) || isset($arguments['verbose']))
  {
    $installer->verbose();
  }

  // Install the Open Semantic Framework
  if(isset($arguments['install-osf']))
  {
    $installer->installOSF();
  }

  // Install the structWSF-PHP-API library
  if(isset($arguments['install-structwsf-php-api']))
  {
    $installer->installStructWSFPHPAPI();
  }

  // Upgrade the structWSF-PHP-API library
  if(isset($arguments['upgrade-structwsf-php-api']))
  {
    $installer->upgradeStructWSFPHPAPI();
  }

  // Install the Datasets Management Tool library
  if(isset($arguments['install-datasets-management-tool']))
  {
    $installer->installDatasetsManagementTool();
  }

  // Upgrade the Datasets Management Tool library
  if(isset($arguments['upgrade-datasets-management-tool']))
  {
    $installer->upgradeDatasetsManagementTool();
  }

  // Install the Ontologies Management Tool library
  if(isset($arguments['install-ontologies-management-tool']))
  {
    $installer->installOntologiesManagementTool();
  }

  // Upgrade the Ontologies Management Tool library
  if(isset($arguments['upgrade-ontologies-management-tool']))
  {
    $installer->upgradeOntologiesManagementTool();
  }
  
  // Install structWSF Tests Suites
  if(isset($arguments['install-structwsf-tests-suites']))
  {
    $installer->installStructWSFTestsSuites();
  }
  
  // Upgrade structWSF Tests Suites
  if(isset($arguments['upgrade-structwsf-tests-suites']))
  {
    $installer->upgradeStructWSFTestsSuites();
  }
  
  // Install Apache2 on the system
  if(isset($arguments['install-apache2']))
  {
    $installer->installApache2();
  }
  
  // Install PHP5 on the system
  if(isset($arguments['install-php5']))
  {
    $installer->installPhp5();
  }
  
  // Install MySQL on the system
  if(isset($arguments['install-mysql']))
  {
    $installer->installMySQL();
  }
  
  // Install PhpMyAdmin on the system
  if(isset($arguments['install-phpmyadmin']))
  {
    $installer->installPhpMyAdmin();
  }
  
  // Install structWSF on the system
  if(isset($arguments['install-structwsf']))
  {
    $installer->installStructWSF();
  }
  
  // Install Virtuoso on the system
  if(isset($arguments['install-virtuoso']))
  {
    $installer->installVirtuoso();
  }
  
  // Install Solr on the system
  if(isset($arguments['install-solr']))
  {
    $installer->installSolr();
  }
  
?>