#!/bin/sh -e
# SOLR auto-start
#
# description: auto-starts solr engine
# processname: solr-structwsf
# pidfile: /var/run/solr-structwsf.pid

NAME="solr"
PIDFILE="/var/run/solr-structwsf.pid"
LOG_FILE="/var/log/solr-structwsf.log"
SOLR_DIR="/usr/share/solr/structwsf"
JAVA_OPTIONS="-Xmx1024m -DSTOP.PORT=8079 -DSTOP.KEY=stopkey -jar start.jar"
JAVA="/usr/bin/java"

start() {
  echo -n "Starting $NAME... "
  if [ -f $PIDFILE ]; then
    echo "is already running!"
  else
    cd $SOLR_DIR
    nohup $JAVA $JAVA_OPTIONS > /dev/null 2> $LOG_FILE &
    sleep 2
    echo `ps -ef | grep -v grep | grep java | awk '{print $2}'` > $PIDFILE
    echo "(Done)"
  fi
  return 0
}

stop() {
  echo -n "Stopping $NAME... "
  if [ -f $PIDFILE ]; then
    cd $SOLR_DIR
    $JAVA $JAVA_OPTIONS --stop
    sleep 2
    rm $PIDFILE
    echo "(Done)"
  else
    echo "can not stop, it is not running!"
  fi
  return 0
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    sleep 5
    start
  ;;

*)
echo "Usage: $0 (start | stop | restart)"
exit 1
;;
esac
